[package]
name = "dice-tray"
description = "A CLI dice roller, that uses persistant structs with internal RNG to modle physical dice. Work in progress."
version = "0.0.1"
edition = "2024"

[dependencies]
rand = "*"
regex = "*"
cli-table = "*"

